from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID, uuid4
from pydantic import BaseModel, Field, field_validator, model_validator


# ==========================================
# 1. State & Lifecycle Enumerations
# ==========================================

class TaskStatus(str, Enum):
    """
    Represents the operational lifecycle states of an AgentTask.
    
    Transitions:
        PENDING -> QUEUED -> RUNNING -> COMPLETED
                                    -> FAILED
                                    -> CANCELLED
                 -> BLOCKED -> RUNNING
    """
    PENDING = "pending"
    QUEUED = "queued"
    RUNNING = "running"
    BLOCKED = "blocked"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ToolStatus(str, Enum):
    """
    Represents the lifecycle transition states of a discrete Tool invocation.
    
    Transitions:
        REQUESTED -> EXECUTING -> SUCCESS
                               -> FAILURE
    """
    REQUESTED = "requested"
    EXECUTING = "executing"
    SUCCESS = "success"
    FAILURE = "failure"


class NodeStatus(str, Enum):
    """
    Lifecycle tracking states of a TaskNode within the execution DAG.
    
    Transitions:
        IDLE -> RUNNING -> COMPLETED
                        -> FAILED
             -> SKIPPED (due to parent failure and lack of recovery path)
    """
    IDLE = "idle"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class MemoryType(str, Enum):
    """
    System Memory partitions utilizing distinct retrieval heuristics and decay curves.
    """
    EPISODIC = "episodic"      # Specific execution footsteps, traces, and tool logs
    SEMANTIC = "semantic"      # Facts, structural requirements, domain knowledge, codebase facts
    PROCEDURAL = "procedural"  # Workflow definitions, step plans, tool schemas, best practices
    WORKING = "working"        # Active execution thread state, current context window buffers


class EventSeverity(str, Enum):
    """
    System event severity grading for routing, auditing, and log metrics.
    """
    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


# ==========================================
# 2. Strongly Typed Schemas (Pydantic models)
# ==========================================

class ToolRequest(BaseModel):
    """
    Payload dispatched to the host runner to invoke a specific system-level capability.
    """
    request_id: UUID = Field(
        default_factory=uuid4,
        description="The unique global tracing identification token for this request."
    )
    task_id: UUID = Field(
        ...,
        description="Reference UUID of the parent AgentTask generating this request."
    )
    tool_name: str = Field(
        ...,
        min_length=1,
        pattern=r"^[a-zA-Z0-9_\-\.]+$",
        description="Namespace identifier of the tool in reverse-dns style or direct naming."
    )
    arguments: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structural schema arguments required for tool execution."
    )
    requested_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC time tag denoting when the runtime dispatched this unit."
    )
    timeout_seconds: int = Field(
        default=300,
        ge=1,
        le=3600,
        description="Enforced runtime sandbox execution timeout threshold."
    )


class ToolResult(BaseModel):
    """
    Unified response enclosing output data, metrics, or errors emitted during tool run.
    """
    result_id: UUID = Field(
        default_factory=uuid4,
        description="The unique transaction ID for this tool execution event."
    )
    request_id: UUID = Field(
        ...,
        description="Corresponding request identification matching the originating ToolRequest."
    )
    status: ToolStatus = Field(
        ...,
        description="Terminal status representing the invocation lifecycle state."
    )
    output: Optional[Any] = Field(
        None,
        description="The structured output payload generated by the tool upon success."
    )
    error: Optional[str] = Field(
        None,
        description="Verbose string error details or stderr trace output if execution fails."
    )
    completed_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC time tag when execution terminated and results were gathered."
    )
    duration_ms: float = Field(
        ...,
        ge=0.0,
        description="Enforced execution telemetry showing exact runtime duration in milliseconds."
    )

    @model_validator(mode="after")
    def validate_terminal_fields(self) -> "ToolResult":
        """
        Enforce alignment of status, outputs, and errors inside result.
        """
        if self.status == ToolStatus.FAILURE and not self.error:
            raise ValueError("Tool execution failure requires an associated error message.")
        if self.status == ToolStatus.SUCCESS and self.error:
            raise ValueError("Successful Tool run cannot contain an error payload.")
        return self


class ProviderRequest(BaseModel):
    """
    Aggregated and structured model parameters dispatched to the routed Model service provider.
    """
    request_id: UUID = Field(
        default_factory=uuid4,
        description="Unique system tracking trace-ID for this service request."
    )
    provider: str = Field(
        ...,
        description="The model service endpoint platform (e.g. 'google-vertex', 'anthropic')."
    )
    model: str = Field(
        ...,
        description="The target model variant requested (e.g. 'gemini-2.5-pro', 'claude-3-5-sonnet')."
    )
    prompt: Union[str, List[Dict[str, Any]]] = Field(
        ...,
        description="Raw prompt string or serialized message list conforming to provider specifications."
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Degree of randomness applied to candidate generation sequences."
    )
    max_tokens: Optional[int] = Field(
        default=None,
        ge=1,
        description="Upper token limit generated before execution terminates."
    )
    system_instruction: Optional[str] = Field(
        None,
        description="System prompt grounding guidelines injected directly in user context namespaces."
    )
    tools: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="JSON Schemas defining internal runtime capabilities declared for LLM function calling."
    )
    sent_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp indicating provider message dispatch."
    )


class ProviderResponse(BaseModel):
    """
    Standardized translation wrapper parsing provider outputs, token consumption tracks, and errors.
    """
    response_id: UUID = Field(
        default_factory=uuid4,
        description="Internal telemetry tracing identification key for this provider action."
    )
    request_id: UUID = Field(
        ...,
        description="The initiating ProviderRequest execution tracing value."
    )
    text: Optional[str] = Field(
        None,
        description="Synthesized natural language or structural response output."
    )
    tool_calls: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Extracted arrays detailing downstream tool invocations generated by the LLM."
    )
    finish_reason: str = Field(
        ...,
        description="Token parsing end state classifier (e.g., 'stop', 'length', 'tool_calls')."
    )
    prompt_tokens: int = Field(
        ...,
        ge=0,
        description="Volume metrics stating consumed input tokens."
    )
    completion_tokens: int = Field(
        ...,
        ge=0,
        description="Volume metrics stating emitted output tokens."
    )
    received_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp indicating response payload receipt and completion."
    )

    @model_validator(mode="after")
    def validate_payload_presence(self) -> "ProviderResponse":
        """
        Enforces that either a natural language output text block or a tool call exists.
        """
        if not self.text and not self.tool_calls:
            raise ValueError("ProviderResponse must supply either text contents or downstream tool_calls.")
        return self


class AgentTask(BaseModel):
    """
    The atomic command/directive assigned to an Orchestrator or Sub-Agent for goal execution.
    """
    task_id: UUID = Field(
        default_factory=uuid4,
        description="Target sequence unique Task tracking reference ID."
    )
    parent_id: Optional[UUID] = Field(
        None,
        description="Super-task trace ID tracking parent delegation linkages."
    )
    title: str = Field(
        ...,
        min_length=2,
        max_length=256,
        description="Short human-friendly workspace title labeling the targeted unit."
    )
    description: str = Field(
        ...,
        description="Detailed, concrete directive describing context, requirements, and evaluation guidelines."
    )
    status: TaskStatus = Field(
        default=TaskStatus.PENDING,
        description="System state variable mapping the task workflow lifecycle location."
    )
    priority: int = Field(
        default=1,
        ge=0,
        le=10,
        description="Heuristic operational tier (0: lowest, 10: absolute priority/hotfix execution)."
    )
    assigned_agent: str = Field(
        ...,
        description="The operational target agent class name (e.g., 'planner', 'coder_agent')."
    )
    inputs: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured parameter properties and workspace context frames mapped into the engine."
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC tracking generation stamp."
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Chronological updated event tracker stamp reflecting transition mutations."
    )

    @field_validator("updated_at", mode="before")
    @classmethod
    def sync_updated_at(cls, v: Any) -> datetime:
        return v or datetime.utcnow()


class AgentResult(BaseModel):
    """
    Terminal output synthesis generated upon completion of an assigned AgentTask.
    """
    result_id: UUID = Field(
        default_factory=uuid4,
        description="The structural tracking transaction UUID."
    )
    task_id: UUID = Field(
        ...,
        description="Originating AgentTask relationship matching key."
    )
    success: bool = Field(
        ...,
        description="Boolean declaring whether the execution criteria met the definition of done."
    )
    output: Dict[str, Any] = Field(
        default_factory=dict,
        description="Aggregated key-value payload outlining target solutions, files, or facts."
    )
    error: Optional[str] = Field(
        None,
        description="Descriptive debugging messages of failure traces if success maps to False."
    )
    resolved_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Verification execution and system callback wrap timing marker."
    )

    @model_validator(mode="after")
    def validate_outcome_consistency(self) -> "AgentResult":
        """
        Verify that a failure output encapsulates a meaningful error message structure.
        """
        if not self.success and not self.error:
            raise ValueError("Unsuccessful task resolutions require a specified failure execution error.")
        if self.success and self.error:
            raise ValueError("Successful task resolution outcomes must not host error trace fields.")
        return self


class TaskNode(BaseModel):
    """
    Container node wrapper forming the nodes of the workflow Execution Directed Acyclic Graph (DAG).
    """
    node_id: UUID = Field(
        default_factory=uuid4,
        description="Node identifier tracking identity inside the structural workflow execution DAG."
    )
    dag_id: UUID = Field(
        ...,
        description="Reference UUID pointing to the execution sequence orchestration flow graph."
    )
    task: AgentTask = Field(
        ...,
        description="Direct nested AgentTask parameters mapping specification for runtime execution."
    )
    dependencies: List[UUID] = Field(
        default_factory=list,
        description="Prerequisite Node IDs that must terminate successfully before this node transitions to queued."
    )
    status: NodeStatus = Field(
        default=NodeStatus.IDLE,
        description="The operational validation state tracker variable."
    )
    started_at: Optional[datetime] = Field(
        None,
        description="Timestamp highlighting the transition into NodeStatus.RUNNING."
    )
    ended_at: Optional[datetime] = Field(
        None,
        description="Timestamp highlighting the transition into NodeStatus.COMPLETED or FAILED."
    )

    @model_validator(mode="after")
    def prevent_self_dependency(self) -> "TaskNode":
        """
        Prevents circular logic loops at the graph parsing execution layer.
        """
        if self.node_id in self.dependencies:
            raise ValueError(f"Graph constraints exception: Node {self.node_id} cannot reference itself as a dependency.")
        return self


class SystemEvent(BaseModel):
    """
    Central event-bus payload logging state shifts, system alerts, and routing metrics.
    """
    event_id: UUID = Field(
        default_factory=uuid4,
        description="Global system tracking payload indicator."
    )
    source: str = Field(
        ...,
        description="The logical system component namespaces triggering the state shift (e.g. 'router.engine')."
    )
    topic: str = Field(
        ...,
        description="Semantic event route identification keyword (e.g. 'task.unblocked')."
    )
    severity: EventSeverity = Field(
        default=EventSeverity.INFO,
        description="Priority mapping grading severity context indicators."
    )
    payload: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary details, diagnostic maps, and telemetry payload."
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Global chronometer registration epoch indicator."
    )


class ExecutionLog(BaseModel):
    """
    Sequential step logs compiled for execution auditing, replay, and agent debugging traces.
    """
    log_id: UUID = Field(
        default_factory=uuid4,
        description="Individual debug trace line identifier value."
    )
    task_id: Optional[UUID] = Field(
        None,
        description="Optional scope identifier anchoring the logging session to a particular task."
    )
    step_number: int = Field(
        ...,
        ge=0,
        description="Chronological step index trace within the specific model agent action chain."
    )
    message: str = Field(
        ...,
        description="The actual structural notification text detailing state changes."
    )
    tool_call_id: Optional[UUID] = Field(
        None,
        description="Optional execution path reference tracking a dispatched system tool ID."
    )
    memory_references: List[UUID] = Field(
        default_factory=list,
        description="Target matching IDs of active or historical semantic memory cells loaded during reasoning."
    )
    logged_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp documenting operational tracking registration."
    )


class MemoryEntry(BaseModel):
    """
    Unit cell stored in context memory structures mapping representations, weights, and embeddings.
    """
    memory_id: UUID = Field(
        default_factory=uuid4,
        description="Vector matching address vector ID for memory store locations."
    )
    type: MemoryType = Field(
        ...,
        description="Classification defining structural decay and architectural access routes."
    )
    content: str = Field(
        ...,
        description="The string serialized structural fact or execution step log description."
    )
    vector_embedding: Optional[List[float]] = Field(
        None,
        description="Optional dense continuous vector embedding representation tracking dimensional mapping."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Scoping keywords, decay timelines, and provenance origin criteria tags."
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Original compilation and absorption timing tag."
    )
    decay_factor: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Salience weight scale factoring decay over retrieval counts and temporal spacing."
    )


class ProjectState(BaseModel):
    """
    Unified project representation documenting the source tree, manifests, and branch structures.
    """
    project_id: UUID = Field(
        default_factory=uuid4,
        description="The workspace execution scope project identifier."
    )
    active_branch: str = Field(
        default="main",
        description="Target git namespace or branch tree tracing model changes."
    )
    file_tree: Dict[str, str] = Field(
        ...,
        description="Map of relative directory system file paths aligned against SHA-256 integrity hash tags."
    )
    dependencies_manifest: Dict[str, str] = Field(
        default_factory=dict,
        description="Packages.json or equivalent module mappings showing explicit configured version ranges."
    )
    config_overrides: Dict[str, Any] = Field(
        default_factory=dict,
        description="Overloaded environmental parameters, API switches, or runtime system settings flags."
    )
    synchronized_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="The last file tree integrity verify-sync execution chronometer tag."
    )
